version: "3"
services:
  bot:
    build: SHET/
    command: python3 ./main.py
    environment:
      - PYTHONUNBUFFERED=True
    depends_on:
      - MDb
  MDb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: SHET_DB
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data_container: